version: '3.8'

services:
  n8n:
    image: pr-cybr/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_TZ=$(cat /etc/timezone)
    volumes:
      - ./n8n:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - pr-cybr-net

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pr-cybr-net

  tunnel:
    image: n8nio/localtunnel
    command: --port 5678
    restart: always
    networks:
      - pr-cybr-net

  pr-cybr-ci-cd-agent:
    image: prcybr/pr-cybr-ci-cd-agent:latest
    container_name: pr-cybr-ci-cd-agent
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - pr-cybr-net
    ports:
      - "8080:80"

volumes:
  postgres_data:

networks:
  pr-cybr-net:
    driver: bridge