name: Build and Publish image to Docker Hub

on:
  push:
    branches:
      - main
    paths: 
      - 'config/Dockerfile'
  workflow_dispatch:

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build image
        run: |
          docker build ./config/ -t prcybr/pr-cybr-ci-cd-agent:latest
      - name: push image to docker hub
        run: |
          docker push prcybr/pr-cybr-ci-cd-agent:latest
