name: "Shared security scanning setup"
description: "Reusable checkout and optional Python environment configuration for security workflows."
inputs:
  python-version:
    description: "Python version to install for tooling. Leave blank to skip."
    required: false
    default: '3.11'
  cache-dependency-path:
    description: "Newline separated glob patterns for Python dependency caching."
    required: false
    default: 'requirements.txt'
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      if: ${{ inputs.python-version != '' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    - name: Upgrade pip
      if: ${{ inputs.python-version != '' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
