name: Deploy and Run n8n Workflow

on:
  push:
    branches:
    - main

jobs:
  deploy-and-run-n8n:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Load .env
      run: |
        echo "N8N_WORKFLOW_WEBHOOK_URL=${{ secrets.N8N_WORKFLOW_WEBHOOK_URL }}" >> $GITHUB_ENV
        echo "SLACK_CHANNEL_NAME=${{ secrets.SLACK_CHANNEL_NAME }}" >> $GITHUB_ENV
        echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> $GITHUB_ENV
        echo "TRIGGER_URL=${{ secrets.TRIGGER_URL }}" >> $GITHUB_ENV
        echo "N8N_USERNAME=${{ secrets.N8N_USERNAME }}" >> $GITHUB_ENV
        echo "N8N_PASSWORD=${{ secrets.N8N_PASSWORD }}" >> $GITHUB_ENV

    - name: Start n8n in Docker
      run: |
        docker pull n8nio/n8n
        docker run -d \
          --name n8n \
          -v $GITHUB_WORKSPACE/.github/workflows/n8n/config/auth.json:/home/node/.n8n/auth.json \
          -v $GITHUB_WORKSPACE/.github/workflows/n8n/workflows:/home/node/.n8n/workflows \
          -e N8N_USERNAME=${{ env.N8N_USERNAME }} \
          -e N8N_PASSWORD=${{ env.N8N_PASSWORD }} \
          -e WEBHOOK_URL=${{ env.N8N_WORKFLOW_WEBHOOK_URL }} \
          -p 5678:5678 n8nio/n8n

    - name: Trigger n8n workflow
      run: |
        curl -X POST ${{ env.N8N_WORKFLOW_WEBHOOK_URL }}/trigger-on-push \
        -H "Content-Type: application/json" \
        -d '{
              "repository": "${{ github.repository }}",
              "branch": "${{ github.ref_name }}",
              "commit": "${{ github.sha }}",
              "author": "${{ github.actor }}"
            }'

    - name: Clean up Docker
      run: |
        docker stop n8n
        docker rm n8n
