on:
  pull_request:
    types: [ opened ]

jobs:
  run_n8n_workflow:
    runs-on: ubuntu-latest
    name: Run n8n Workflow
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Load .env
      run: |
        echo "N8N_ENCRYPTION_KEY=${{ secrets.N8N_ENCRYPTION_KEY }}" >> $GITHUB_ENV

    - name: Get PR Commit Details
      id: pr_commit
      run: |
        COMMIT_SHA=$(jq -r '.pull_request.head.sha' $GITHUB_EVENT_PATH)
        AUTHOR=$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
        echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
        echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV

    - name: Run n8n Workflow
      run: |
        curl -X POST ${{ secrets.N8N_WORKFLOW_WEBHOOK_URL }}/notify-slack \
        -H "Content-Type: application/json" \
        -d '{
              "repository": "https://github.com/${{ github.repository }}",
              "commit": "${{ env.COMMIT_SHA }}",
              "author": "${{ env.AUTHOR }}"
            }'
        curl -X POST ${{ secrets.N8N_WORKFLOW_WEBHOOK_URL }}/notify-discord \
        -H "Content-Type: application/json" \
        -d '{
              "repository": "https://github.com/${{ github.repository }}",
              "commit": "${{ env.COMMIT_SHA }}",
              "author": "${{ env.AUTHOR }}"
            }'
