name: maintenance

on:
  workflow_dispatch:   # manual trigger
  schedule:            # optional: run daily at 02:00 UTC
    - cron: "0 2 * * *"
  push:
    branches: [ codex, agents, dev ]
  pull_request:
    branches: [ main ]

jobs:
  maintenance:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y git python3 python3-pip

      - name: Clone repo
        run: |
          git clone https://github.com/${{ github.repository }} /workspace

      - name: Run maintenance.py if present
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_TASK_DB: ${{ secrets.NOTION_TASK_DB }}
          NOTION_PR_DB: ${{ secrets.NOTION_PR_DB }}
          NOTION_PROJECT_DB: ${{ secrets.NOTION_PROJECT_DB }}
          NOTION_DISCUSSION_DB: ${{ secrets.NOTION_DISCUSSION_DB }}
        run: |
          cd /workspace
          if [ -f maintenance.py ]; then
            echo "🔧 Running maintenance script..."
            python3 maintenance.py
          else
            echo "⚠️ No maintenance.py found, skipping."
          fi
