name: N8N Setup Test

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - main

jobs:
  build-base-image:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Base Image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./docker/images/n8n-base/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/n8n-base:latest

  test-postgres:
    name: Test Postgres
    runs-on: ubuntu-latest
    needs: build-base-image
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: n8n
          POSTGRES_PASSWORD: n8n
          POSTGRES_DB: n8n
        options: >-
          --health-cmd "pg_isready -U n8n"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Run Postgres Tests
        run: |
          docker-compose up -d
          docker-compose exec n8n n8n audit
          docker-compose exec n8n curl -f http://localhost:5678/healthz

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [build-base-image, test-postgres]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install --prefix=.github/scripts --no-package-lock

      - name: Run Test Scripts
        run: node .github/scripts/check-tests.mjs